sudo: false
language: node_js
node_js:
  - "4.2"

script:
  # DEV: Currently our test suite runs locally only
  #   This should be resolved in #19
  - npm run lint

notifications:
  email:
    recipients:
      - samuel.r.attard@gmail.com
    on_success: change
    on_failure: change
